# experiment config
experiment_name: "vqvae-ce buffer fix" # name of the experiment
description: "" # description of the experiment
seed: 42 # seed for reproducibility
test_interval: 1 # test the model every test_interval epochs, None to disable
vis_train_interval: 1 # plot the training loss every plot_train_interval epochs, None to disable
wandb_log: true # log the experiment to wandb

#dataset config
n_train: 100000 # number of training samples
n_test: 5000 # number of test samples
dataset: "imagenet" # either cifar or imagenet
class_idx: null # list of class indices to use, empty list to use all classes
hyperclass: false # use hyperclasses

# train config
batch_size: 32
epochs: 20
learning_rate: 0.0001
label_conditioning: false
convergence_patience: 3
convergence_performance_threshold: 0.999
convergence_key: Reconstruction

# model config
model_name: "vqvae-ce" # either autoencoder or vae

# PixelCNN
# model_config:
#   hidden_chan: 128
#   num_codes: 512
#   num_classes: 7
#   input_shape: [32, 32]  # for mnist
#   conditional_embedding_dim: 16
#   conditional: True
#   vqvae_path: artifacts/konni_replacement_vqvae
#   use_one_hot: False
#   use_code_embeddings: True

# VQVAE
model_config:
  codebook_size: 1024
  commitment_weight: 4
  hidden_dimension: 256
  embedding_dimension: 256
  codebook_initialization_radius: 0.5
  # optional for vqvae-ce
  buffer_size: 20
  max_idle_weight: 5

# VAE
# model_config:
#   kld_weight: 0.00025
#   latent_dimension: 2
#   hidden_dimension: 128
