experiment:
  name: "pixelcnn on mnist" # name of the experiment
  description: "" # description of the experiment
  seed: 42 # seed for reproducibility
  test_interval: 1  # test the model every test_interval epochs, None to disable
  vis_train_interval: 1 # plot the training loss every plot_train_interval epochs, None to disable
  wandb_log: True # log the experiment to wandb

data:
  n_train: null # number of training samples
  n_test: null # number of test samples
  dataset: "mnist" # either cifar or imagenet or mnist
  class_idx: null # list of class indices to use, empty list to use all classes

train:
  batch_size: 128
  epochs: 3
  learning_rate: 0.0002

model:
  model_name: "pixelcnn" # either autoencoder or vae
  