experiment:
  name: "vqvae" # name of the experiment
  description: "" # description of the experiment
  seed: 45 # seed for reproducibility
  test_interval: 1  # test the model every test_interval epochs, None to disable
  vis_train_interval: 1 # plot the training loss every plot_train_interval epochs, None to disable
  wandb_log: True # log the experiment to wandb

data:
  n_train: 60000 # number of training samples
  n_test: 1000 # number of test samples
  dataset: "imagenet" # either cifar or imagenet
  class_idx: null # list of class indices to use, empty list to use all classes

train:
  batch_size: 128
  epochs: 15
  learning_rate: 0.0002

model:
  model_name: "vqvae" # either autoencoder or vae
  