experiment:
  name: "BaselineAutoencoder" # name of the experiment
  description: "First attempt to train BaselineAutoencoder" # description of the experiment
  seed: 42 # seed for reproducibility
  test_interval: 5  # test the model every test_interval epochs, None to disable
  vis_train_interval: 5 # plot the training loss every plot_train_interval epochs, None to disable
  wandb_log: True # log the experiment to wandb

data:
  n_train: 10 # number of training samples
  n_test: 10 # number of test samples
  dataset: "cifar" # either cifar or imagenet

train:
  batch_size: 10
  epochs: 5
  learning_rate: 0.01

model:
  model_name: "autoencoder" # either autoencoder or vae
  